/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VentasIndexRouteImport } from './routes/ventas/index'
import { Route as ProductosIndexRouteImport } from './routes/productos/index'
import { Route as MostradorIndexRouteImport } from './routes/mostrador/index'
import { Route as ProductosNewRouteImport } from './routes/productos/new'
import { Route as ProductosProductoIdEditRouteImport } from './routes/productos/$productoId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasIndexRoute = VentasIndexRouteImport.update({
  id: '/ventas/',
  path: '/ventas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MostradorIndexRoute = MostradorIndexRouteImport.update({
  id: '/mostrador/',
  path: '/mostrador/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosNewRoute = ProductosNewRouteImport.update({
  id: '/productos/new',
  path: '/productos/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosProductoIdEditRoute = ProductosProductoIdEditRouteImport.update({
  id: '/productos/$productoId/edit',
  path: '/productos/$productoId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/productos/new': typeof ProductosNewRoute
  '/mostrador/': typeof MostradorIndexRoute
  '/productos/': typeof ProductosIndexRoute
  '/ventas/': typeof VentasIndexRoute
  '/productos/$productoId/edit': typeof ProductosProductoIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/productos/new': typeof ProductosNewRoute
  '/mostrador': typeof MostradorIndexRoute
  '/productos': typeof ProductosIndexRoute
  '/ventas': typeof VentasIndexRoute
  '/productos/$productoId/edit': typeof ProductosProductoIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/productos/new': typeof ProductosNewRoute
  '/mostrador/': typeof MostradorIndexRoute
  '/productos/': typeof ProductosIndexRoute
  '/ventas/': typeof VentasIndexRoute
  '/productos/$productoId/edit': typeof ProductosProductoIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/productos/new'
    | '/mostrador/'
    | '/productos/'
    | '/ventas/'
    | '/productos/$productoId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/productos/new'
    | '/mostrador'
    | '/productos'
    | '/ventas'
    | '/productos/$productoId/edit'
  id:
    | '__root__'
    | '/'
    | '/productos/new'
    | '/mostrador/'
    | '/productos/'
    | '/ventas/'
    | '/productos/$productoId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductosNewRoute: typeof ProductosNewRoute
  MostradorIndexRoute: typeof MostradorIndexRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
  VentasIndexRoute: typeof VentasIndexRoute
  ProductosProductoIdEditRoute: typeof ProductosProductoIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas/': {
      id: '/ventas/'
      path: '/ventas'
      fullPath: '/ventas/'
      preLoaderRoute: typeof VentasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mostrador/': {
      id: '/mostrador/'
      path: '/mostrador'
      fullPath: '/mostrador/'
      preLoaderRoute: typeof MostradorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/new': {
      id: '/productos/new'
      path: '/productos/new'
      fullPath: '/productos/new'
      preLoaderRoute: typeof ProductosNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$productoId/edit': {
      id: '/productos/$productoId/edit'
      path: '/productos/$productoId/edit'
      fullPath: '/productos/$productoId/edit'
      preLoaderRoute: typeof ProductosProductoIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductosNewRoute: ProductosNewRoute,
  MostradorIndexRoute: MostradorIndexRoute,
  ProductosIndexRoute: ProductosIndexRoute,
  VentasIndexRoute: VentasIndexRoute,
  ProductosProductoIdEditRoute: ProductosProductoIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
